- name: Test cert repo access
  run: |
    git clone https://${{ secrets.MATCH_GIT_URL }} /tmp/test-clone \
      -c http.extraheader="Authorization: Basic ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" \
      --depth 1
